version: '3'

services:
  django:
    # Сборка образа для сервиса django из текущей директории
    build: .
    # Задание имени контейнера для сервиса django
    container_name: pc_builder
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: bash -c "service ssh start && ls -a && python manage.py runserver 0.0.0.0:8000"
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    volumes:
      - ./pc_builder2/:/srv/app/
      - ./.env:/srv/app/.env
    networks:
      - default
    ports:
      - '8000:8000'
      - '22:22'
    # Зависимость от другого сервиса
    depends_on:
      - postgres

  postgres:
    # Использование готового образа postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB}
    # Задание переменных окружения для контейнера с postgres
    networks:
      - default
     # Задание имени контейнера для сервиса pgdb
    container_name: postgres
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/


  pgadmin:
    image: dpage/pgadmin4

    env_file:
      - ./.env

    container_name: pgadmin

    ports:
      - 5050:80

    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  pgdbdata: null

networks:
  default:
    driver: bridge
