# Generated by Django 5.1.1 on 2024-10-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basecpu",
            name="tdp",
            field=models.IntegerField(null=True, verbose_name="Пакет тепловыделения"),
        ),
        migrations.AlterField(
            model_name="basecpu",
            name="is_graphics",
            field=models.BooleanField(null=True, verbose_name="Сокращенное название"),
        ),
        migrations.AlterField(
            model_name="basecpu",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Сокращенное название"),
        ),
        migrations.AlterField(
            model_name="basecpu",
            name="perfomance_index",
            field=models.FloatField(verbose_name="Индекс производительности"),
        ),
        migrations.AlterField(
            model_name="basecpu",
            name="socket",
            field=models.CharField(verbose_name="Сокет"),
        ),
        migrations.AlterField(
            model_name="basegpu",
            name="perfomance_index",
            field=models.FloatField(verbose_name="Индекс производительности"),
        ),
        migrations.AlterField(
            model_name="basegpu",
            name="tdp",
            field=models.IntegerField(null=True, verbose_name="Пакет тепловыделения"),
        ),
    ]
